# Generated by Django 2.1.2 on 2018-10-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.CharField(max_length=32, verbose_name='创建人')),
                ('action', models.CharField(max_length=32, verbose_name='动作')),
                ('info', models.CharField(max_length=32, verbose_name='信息')),
                ('parameter', models.CharField(max_length=32, verbose_name='参数')),
                ('status', models.CharField(max_length=32, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务列表',
                'verbose_name_plural': '任务列表',
            },
        ),
    ]
